protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';
    public $banned = false;
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','getvkuserid','update','groups','cgroups','registration','authorization','complaints','mycomplaints','answer'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','banUser','unBanUser','create','checkAnswer'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

    public function actionGroups($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Group']))
        {
            $model->attributes=$_POST['Group'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('groups',array(
            'model'=>$model,
        ));
    }

    public function actionCgroups($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Group']))
        {
            $model->attributes=$_POST['Group'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('cgroups',array(
            'model'=>$model,
        ));
    }

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
        $model = $this->loadModel($id);
        $user_id = User::model()->getUserId();
        $friends = array();
        if (($model->id == $user_id) && !empty($model->service) && in_array($model->service, array('facebook', 'vkontakte'))) {
            $service = Yii::app()->eauth->getIdentity($model->service);
            $service->authenticate();
            if ($model->service == 'facebook') {
                $facebookFriends = $service->makeSignedRequest('https://graph.facebook.com/me/friends');
                $serviceFriendsIds = array();
                foreach ($facebookFriends->data as $facebookFriend) {
                    $serviceFriendsIds[] = $facebookFriend->id;
                }

            } else {
                $serviceResponse = $service->makeSignedRequest('https://api.vk.com/method/friends.get.json', array(
                    'query' => array(
                        'uid' => $model->serv_id,
                    )
                ));
                $serviceFriendsIds = $serviceResponse->response;
            }
            $criteria = new CDbCriteria();
            $criteria->addCondition('service = :currentService');
            $criteria->params[':currentService'] = $model->service;
            $criteria->addInCondition('serv_id', $serviceFriendsIds);
            $friends = User::model()->findAll($criteria);
        }
		$this->render('view',array(
			'model'=> $model,
            'user_id' => $user_id,
            'friends' => $friends
		));
	}
	public function actionComplaints($id)
	{
        $model = $this->loadModel($id);
        $user_id = User::model()->getUserId();
		if ($model->id != $user_id){
			throw new CHttpException(403,'The requested page does not exist.');
		} 
		$complaints = Complaint::complaintsList($user_id);
		$this->render('view',array(
			'model'=> $model,
			'user_id' => $user_id,
			'complaints' => $complaints
		));
	}
	public function actionMycomplaints()
	{
        $user_id = User::model()->getUserId();
        $model = $this->loadModel($user_id);
		$complaints = Complaint::MyComplaintsList($user_id);
		$this->render('view',array(
			'model'=> $model,
			'user_id' => $user_id,
			'complaints' => $complaints
		));
	}
	public function actionAnswer($complaint)
	{
        $user_id = User::model()->getUserId();
		$db = Yii::app()->db;
        $command = $db->createCommand();
		$command->from('complaint');
		$command->where('complaint.id = '.(int)$complaint);
		$resalt = $command->queryRow();
        if($resalt['text_id'] != 'user'){
			$groupModel = Group::model();
			$groupsIds = $groupModel->getAllUsersGroupsIds($user_id);
			$meetsIds  = $groupModel->getMeetsIdsWhereUserIsAdmin($groupsIds);
			$ids = array_merge($groupsIds, $meetsIds);
		}
		if($resalt['user_id'] != $user_id){
			if($resalt['text_id'] == 'user' && $resalt['item_id'] != $user_id)
				throw new CHttpException(403,'The requested page does not exist.');
			if($resalt['text_id'] != 'user' && !in_array($resalt['item_id'], $ids))
				throw new CHttpException(403,'The requested page does not exist.');
		}
		$model = $this->loadModel($user_id);
		$complaint = Complaint::model()->getFormatedComplaintRecords($complaint);
		//fb($complaint, 'complaint');exit;
		$this->render('view',array(
			'model'=> $model,
			'user_id' => $user_id,
			'complaint' => $complaint
		));
	}
	public function actionCheckAnswer($complaint)
	{
		//$user_id = User::model()->getUserId();
		$db = Yii::app()->db;
        $command = $db->createCommand();
		$command->from('complaint');
		$command->where('complaint.id = '.(int)$complaint);
		$resalt = $command->queryRow();
		$user_id = $resalt['user_id'];
        //fb($user_id,$complaint);exit;
		$model = $this->loadModel($user_id);
		$complaint = Complaint::model()->getFormatedComplaintRecords($complaint);
		//fb($complaint, 'complaint');exit;
		$this->render('view',array(
			'model'=> $model,
			'user_id' => $user_id,
			'complaint' => $complaint
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		//$this->layout='//layouts/column2admin';		
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
            $attributes = array('name', 'email', 'city', 'city_id', 'region_id', 'country_id', 'pass', 'reg_date', 'birthday', 'sex','answer_comment_notice');

            $model->name  = $_POST['User']['name'];
            $model->email = $_POST['User']['email'];
            $model->city  = $_POST['User']['city'];
            $model->country_id  = $_POST['User']['country_id'];
            if($model->country_id)
				$model->region_id  = $_POST['User']['region_id'];
			$model->city_id = $_POST['User']['city_id'];
			if($model->city && $model->city_id && $model->region_id){
				$criteria = new CDbCriteria();
				$criteria->condition='name=:name AND region_id=:region_id';
				$criteria->params=array(':name'=>$model->city,':region_id'=>$model->region_id);
				$city_model = City::model()->find($criteria);
				if($city_model === null){
					$model->city  = '';
				}else{
					$model->city = $city_model->name;
				}
			}
			if($model->city && !$model->city_id && $model->region_id){
				$criteria = new CDbCriteria();
				$criteria->condition='name=:name AND region_id=:region_id';
				$criteria->params=array(':name'=>$model->city,':region_id'=>$model->region_id);
				
				$city_model = City::model()->find($criteria);
				if($city_model === null){
					$model->city  = '';	
				}else{
					$model->city_id = $city_model->id;
				}	
			}
            $model->sex   = $_POST['User']['sex'];
            $model->birthday = $_POST['User']['birthday']
                ? date('Y-m-d', strtotime($_POST['User']['birthday']))
                :  '';
            $model->reg_date = date('Y-m-d');
            $model->answer_comment_notice = $_POST['User']['answer_comment_notice'];
            //$model->pass  = $_POST['User']['pass'];

            if ($_FILES['User']['name']['avatar']) {

                //print_r($model->uploadAvatar($id, $_FILES['User']['name']['avatar'])); die;

			    $model->avatar =   $_POST['User']["avatar"] = $model->uploadAvatar($id, $_FILES['User']['name']['avatar']);
                $attributes[] = 'avatar';
            }
            if($model->save(true, $attributes)) {
                $this->redirect('admin');
            }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{	
        $model = $this->loadModel($id);
        $userId = $model->getUserId();//сразу перенаправляет и не дает возможности сохранить пароль
		$isAdmin = Admin::model()->isSiteAdmin($userId);

        if ($userId !== $id && !$isAdmin) {
            $this->redirect(array('view','id'=>$userId));
        };

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
          /*  $avatar = $_POST['User']['avatar'];

            if ($avatar != '') {
                $uploadedFile=CUploadedFile::getInstance($model,'avatar');
                $fileName = "$model->id";
                $model->avatar = $fileName;
            }*/
			if(empty($_POST['User']['serv_id']))

protected/views/user/_complaints.php
<?php
function showCommentsRecursive($comments, $ets = true)
{
    static $user_id = -1;
    if ($user_id == -1) {
        $user_id = User::model()->getUserId();
    }

    foreach($comments as $comment):
        if (empty($comment['text'])) {
            continue;
        }
        $date = explode(' ', CHtml::encode($comment['date']));
        $date[0] = '<strong>' . CHtml::encode(date('d.m.Y', strtotime($date[0]))) . '</strong> ';
        $date = implode($date);

        $answerModificator = empty($comment['children'])
            ? ''
            : 'b-comment__answer_border';
        ?>
        <div class="b-comment" id="comment-<?php echo CHtml::encode($comment['id']); ?>">
            <div class="b-comment__content">
                <div class="b-comment__head">
                    <div class="b-comment__author">
                        <a href="<?php echo Yii::app()->createUrl('user/view') . '/' . urlencode($comment['sender_id']); ?>"
                           target="_blank"><?php echo CHtml::encode($comment['sender_name']); ?></a>
                    </div>
                    <div class="b-comment__date">[<?php echo $date; ?>]</div>
                </div><!-- .b-comment__head-->
                <div class="b-comment__body"><?php echo CHtml::encode($comment['text']); ?></div>
            </div><!-- .b-comment__content-->
            <div class="b-comment__answer <?php echo $answerModificator; ?>" id="answer-<?php echo (int)$comment['id']; ?>">
                <div class="b-comment__answer-form-block"></div>
                <?php if (!empty($comment['children'])): ?>
                    <div class="b-comment__answer-body">
                        <?php showCommentsRecursive($comment['children'], false); ?>
                    </div><!-- .b-comment__answer-body-->
                <?php endif; ?>
            </div><!-- .b-comment__answer-->
			
        </div><!-- .b-comment-->
                <?php if ($user_id && $ets): ?>
					<br>
					<a href="#" class="c-comment__answer-open" onclick="return false;">Ответить</a>
					<form action="<?= Yii::app()->request->baseUrl.'/complaint/sendRecord'; ?>" method="post">
						<textarea class="b-comment__answer-textarea f-left" name="text"></textarea><br>
						<input class="b-comment__answer-submit f-right" type="image" src="/images/send-comment.png" />
						<input type="hidden" name="item_id" value="<?= CHtml::encode($comment['item_id']) ?>" />
						<input type="hidden" name="sender_id" value="<?= CHtml::encode($user_id); ?>" />
						<input type="hidden" name="YII_CSRF_TOKEN" value="<?= Yii::app()->request->csrfToken ?>" />
						<input type="hidden" name="parent_id" value="<?= CHtml::encode($comment['id']) ?>" />
						<input type="hidden" name="text_id" value="<?= CHtml::encode($comment['text_id']) ?>" />
						<div class="clear"></div>
					</form>
                <?php endif; ?>
    <?php
    endforeach;
}
$this->setPageTitle('Ответ на жалобу');
$listUrl = $this->route == 'user/complaints' ? Yii::app()->createUrl('user/complaints', array('id'=>$model->id)) : Yii::app()->createUrl('user/mycomplaints');
$listName = $this->route == 'user/complaints' ? 'Поступившие жалобы' : 'Мои жалобы';
$this->breadcrumbs=array(
	$model->name => Yii::app()->createUrl('user/view', array('id'=>$model->id)),
	$listName => $listUrl,
	'Ответ на жолобу',
);
$compid = $_GET['complaint'];
if($complaint[$compid]['text_id'] == 'group' || $complaint[$compid]['text_id'] == 'meet'){
	$groupModel = Group::model();
	$accusedName = $groupModel->getGroupName($complaint[$compid]['item_id']);
	if($complaint[$compid]['text_id'] == 'group'){
		$accusedLink = Yii::app()->createUrl('group/view', array('id'=>$complaint[$compid]['item_id']));
		$compstr = "группу <a href=\"$accusedLink\">$accusedName</a>";
	}else{
		$accusedLink = Yii::app()->createUrl('group/meet', array('id'=>$complaint[$compid]['parent_id'], 'mid' => $complaint[$compid]['item_id']));
		$compstr = "встречу <a href=\"$accusedLink\">$accusedName</a>";
	}
}else{
	//$userModel = Group::model();
	//$accusedName = $groupModel->getUserName($complaint['item_id']);
	if($complaint[$compid]['user_id'] == $user_id)
		$compstr = ' <a href="'. Yii::app()->createUrl('user/view', array('id'=>$complaint[$compid]['item_id'])).'">'.User::model()->getName($complaint[$compid]['item_id']).'</a>';
	else	
		$compstr = ' Вас';
}
$h2 = $user_id != $complaint[$compid]['user_id'] || $this->route == 'user/checkAnswer' ? 'Жалоба на ' . $compstr . ' от <a href="'.Yii::app()->createUrl('user/view', array('id'=>$complaint[$compid]['user_id'])).'">'.$complaint[$compid]['sender_name'].'</a> ' : 'Жалоба на '.$compstr;
?>
<section id="group-content" class="f-left">
	<div class="content-block-wrap">
		<h2 class="sharp" style="padding-left: 30px;" id="comments"><?=$h2?></h2>
		<div class="content-block">
			<?php
			echo $this->route == 'user/checkAnswer' ? '<a href="'.Yii::app()->createUrl('complaint/resolve', array('id'=>$complaint[$compid]['id'])).'" style="float:right;"> [<b>Пометить как "решено"</b>]</a>' : '';
			showCommentsRecursive($complaint);

			if ($user_id):
			?>
				<!--<form id="wall-form" action="<?php echo Yii::app()->request->baseUrl; ?>/wall/sentRecord"
					  name="sent-record" method="post">
					<textarea class="b-comment__textarea f-left" name="text"></textarea><br>
					<input class="f-right" type="image" src="/images/send-comment.png" />
					<input type="hidden" name="user_id" value="<?php echo CHtml::encode($model->id); ?>" />
					<input type="hidden" name="sender_id" value="<?php echo CHtml::encode($user_id); ?>" />
					<input type="hidden" name="YII_CSRF_TOKEN" value="<?php echo Yii::app()->request->csrfToken; ?>" />-->
				</form>
			<?php endif; ?>
		</div>
	</div>
</section>

protected/views/user/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>
    <table class="b-form-table">
        <tr>
            <td><?php echo $form->label($model,'id'); ?></td>
            <td><?php echo $form->textField($model,'id'); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->label($model,'serv_id'); ?></td>
            <td><?php echo $form->textField($model,'serv_id'); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->label($model,'service'); ?></td>
            <td><?php echo $form->textField($model,'service',array('size'=>50,'maxlength'=>50)); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->label($model,'name'); ?></td>
            <td><?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->label($model,'reg_date'); ?></td>
            <td><?php echo $form->textField($model,'reg_date'); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->label($model,'email'); ?></td>
            <td><?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>100)); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->label($model,'pass'); ?></td>
            <td><?php echo $form->passwordField($model,'pass',array('size'=>32,'maxlength'=>32)); ?></td>
        </tr>
        <div class="row submit">
            <?php echo CHtml::submitButton('Поиск'); ?>
        </div>
    </table>
<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<?php
/* @var $this UserController */
/* @var $data User */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('serv_id')); ?>:</b>
	<?php echo CHtml::encode($data->serv_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('service')); ?>:</b>
	<?php echo CHtml::encode($data->service); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('reg_date')); ?>:</b>
	<?php echo CHtml::encode($data->reg_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('pass')); ?>:</b>
	<?php echo CHtml::encode($data->pass); ?>
	<br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('sex')); ?>:</b>
    <?php echo CHtml::encode($data->sex); ?>
    <br />


</div>

protected/views/user/cgroups.php
<?php
/* @var $this GroupController */
/* @var $data Group */

$user_id = User::model()->getUserId();

?>

<h1 class="page-title sharp align-center"><? echo Yii::t('var', 'Создатель групп');?></h1>
<div class="center vse-uchastniki-admin vse-uchastniki">
    <?
    $dataReader = Group::model()->getUserAdminGroupList($model->id);
    echo '<div style="width:100%;float: left">';
    foreach($dataReader as $row) {
        $avatar = $row['picture'];
        if ($avatar && $avatar != '') ; else $avatar = 'no-pic.png';
        ?>
        <a class="participants f-left white-block align-center" title="#" href="<? echo Yii::app()->createUrl('site/index').'/group/'.urlencode($row['id']); ?>">
            <img src="/images/group/mini_<? echo CHtml::encode($avatar); ?>" alt="event">
            <p class="participants-name f-left"><? echo CHtml::encode($row['name']); ?><br /></p>
        </a>
    <?
    }
    echo '</div>';
    ?>
</div>

protected/views/user/complaints_list.php
<style type="text/css">
	.complaintsBlock{
		margin-bottom:10px;
	}
	.complaintsHeader{
		/* background: #eee; */
		border-bottom:1px solid #388ECD;
	}
	.complaintsBody{
	
	}
	.red{
		color:red;
	}
	.green{
		color:green;
	}
	#complaintsMenu{
		margin-bottom:10px;
		padding:5px 0 0 0;
		background: #fff;
		border-bottom:1px solid #0e8eab;
	}
	#complaintsMenu li{
		display:block;
		float:left;
		margin:0 10px;
		padding:5px 0;
	}
	#complaintsMenu li.activeComplaints{
		background: #0e8eab;
	}
	#complaintsMenu li a{
		padding:0 5px;
	}
	#complaintsMenu li.activeComplaints a{
		background: #0e8eab;
		color:#fff;
	}
</style>
<?php
$this->setPageTitle('Список жалоб');
$listName = $this->route == 'user/complaints' ? 'Поступившие жалобы' : 'Мои жалобы';
$this->breadcrumbs=array(
	$model->name => Yii::app()->createUrl('user/view', array('id'=>$model->id)),
	$listName,
);
?>
<section id="group-content" class="f-left">
	<div class="content-block-wrap">
		<!--<h2 class="sharp" style="padding-left: 30px;" id="comments">Жалобы</h2>-->
		<ul id="complaintsMenu">
			<li class="<?= $this->route == 'user/complaints' ? 'activeComplaints ' : '' ?>complaintsMenuItem"><a href="<?= Yii::app()->createUrl('user/complaints', array('id'=>$user_id));?>">Поступившие жалобы</a></li>
			<li class="<?= $this->route == 'user/mycomplaints' ? 'activeComplaints ' : '' ?>complaintsMenuItem"><a href="<?= Yii::app()->createUrl('user/mycomplaints');?>">Мои жалобы</a></li>
		</ul>
		<div class="content-block">
			<?php 
				//$complaints = Complaint::complaintsList($user_id);
				$count = count($complaints);
				if(!empty($complaints)):
					foreach($complaints as $complaint): 
						if($complaint['text_id'] == 'group' || $complaint['text_id'] == 'meet'){
							$groupModel = Group::model();
							$accusedName = $groupModel->getGroupName($complaint['item_id']);
							if($complaint['text_id'] == 'group'){
								$accusedLink = Yii::app()->createUrl('group/view', array('id'=>$complaint['item_id']));
								$compstr = "группу <a href=\"$accusedLink\">$accusedName</a>";
							}else{
								$accusedLink = Yii::app()->createUrl('group/meet', array('id'=>$complaint['parent_id'], 'mid' => $complaint['item_id']));
								$compstr = "встречу <a href=\"$accusedLink\">$accusedName</a>";
							}
						}else{
							//$userModel = Group::model();
							//$accusedName = $groupModel->getUserName($complaint['item_id']);
							$compstr = 'Вас';
						}
					?>
					<div class="complaintsBlock">
						<div class="complaintsHeader">
							<span><i><?= '<a href="'.Yii::app()->createUrl('user/view', array('id'=>$complaint['sender_id'])).'">'.$complaint['sender_name'].'</a> '.CHtml::encode(date('d.m.Y', strtotime($complaint['date']))).' пожаловался на '.$compstr;?></i></span>
							
							<span class="b-comment__date <?=  $complaint['status'] == 0 ? 'red' : 'green'; ?>"><?=  $complaint['status'] == 0 ? '[Не решено]' : '[Решено]'; ?></span>
						</div>
						<div class="complaintsBody">
						<?= $complaint['text'];?>
							<?php
							$count = Complaint::getCountOfAnswers($complaint['id'], $user_id);
							$countStr = $count >= 1 ? 'Вы отвечали' : '<b>Нет ответов</b>';
							echo $complaint['status'] == 0 ? '<span><a href="'.Yii::app()->createUrl('user/answer', array('complaint'=>$complaint['id'])).'"> Ответить ('.$countStr.')</a> </span>' : '<span><a href="'.Yii::app()->createUrl('user/answer', array('complaint'=>$complaint['id'])).'"> Просмотреть</a> </span>';
							?>	
						</div>
					</div>
						
						
					
				<?php endforeach;
				else:
					echo 'Нет жалоб';
				endif;
			
			?>
		</div>
	</div>
</section>

protected/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Пользователи'=>array('admin'),
	'Создать',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);

?>


<div class="center">
    <div class="white-block">
        <h1 class="align-center">Создать пользователя</h1>
        <?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
    </div>
</div>

protected/views/user/mycomplaints_list.php
<style type="text/css">
	.complaintsBlock{
		margin-bottom:10px;
	}
	.complaintsHeader{
		/* background: #eee; */
		border-bottom:1px solid #388ECD;
	}
	.complaintsBody{
	
	}
	.red{
		color:red;
	}
	.green{
		color:green;
	}
	#complaintsMenu{
		margin-bottom:10px;
		padding:5px 0 0 0;
		background: #fff;
		border-bottom:1px solid #0e8eab;
	}
	#complaintsMenu li{
		display:block;
		float:left;
		margin:0 10px;
		padding:5px 0;
	}
	#complaintsMenu li.activeComplaints{
		background: #0e8eab;
	}
	#complaintsMenu li a{
		padding:0 5px;
	}
	#complaintsMenu li.activeComplaints a{
		background: #0e8eab;
		color:#fff;
	}
</style>
<?php
$this->setPageTitle('Список жалоб');
$listName = $this->route == 'user/complaints' ? 'Поступившие жалобы' : 'Мои жалобы';
$this->breadcrumbs=array(
	$model->name => Yii::app()->createUrl('user/view', array('id'=>$model->id)),
	$listName,
);
?>
<section id="group-content" class="f-left">
	<div class="content-block-wrap">
		<!--<h2 class="sharp" style="padding-left: 30px;" id="comments">Жалобы</h2>-->
		<ul id="complaintsMenu">
			<li class="<?= $this->route == 'user/complaints' ? 'activeComplaints ' : '' ?>complaintsMenuItem"><a href="<?= Yii::app()->createUrl('user/complaints', array('id'=>$user_id));?>">Поступившие жалобы</a></li>
			<li class="<?= $this->route == 'user/mycomplaints' ? 'activeComplaints ' : '' ?>complaintsMenuItem"><a href="<?= Yii::app()->createUrl('user/mycomplaints');?>">Мои жалобы</a></li>
		</ul>
		<div class="content-block">
			<?php 
				//$complaints = Complaint::complaintsList($user_id);
				$count = count($complaints);
				if(!empty($complaints)):
					foreach($complaints as $complaint): 
						if($complaint['text_id'] == 'group' || $complaint['text_id'] == 'meet'){
							$groupModel = Group::model();
							$accusedName = $groupModel->getGroupName($complaint['item_id']);
							if($complaint['text_id'] == 'group'){
								$accusedLink = Yii::app()->createUrl('group/view', array('id'=>$complaint['item_id']));
								$compstr = "группу <a href=\"$accusedLink\">$accusedName</a>";
							}else{
								$accusedLink = Yii::app()->createUrl('group/meet', array('id'=>$complaint['parent_id'], 'mid' => $complaint['item_id']));
								$compstr = "встречу <a href=\"$accusedLink\">$accusedName</a>";
							}
						}else{
							//if($complaint[$compid]['user_id'] == $user_id)
							$compstr = '<a href="'. Yii::app()->createUrl('user/view', array('id'=>$complaint['item_id'])).'">'.User::model()->getName($complaint['item_id']).'</a>';;
							//$userModel = Group::model();
							//$accusedName = $groupModel->getUserName($complaint['item_id']);
						}
					?>
					<div class="complaintsBlock">
						<div class="complaintsHeader">
							<span><i><?= CHtml::encode(date('d.m.Y', strtotime($complaint['date']))).' вы пожаловались на '.$compstr;?></i></span>
							
							<span class="b-comment__date <?=  $complaint['status'] == 0 ? 'red' : 'green'; ?>"><?=  $complaint['status'] == 0 ? '[Не решено]' : '[Решено]'; ?></span>
						</div>
						<div class="complaintsBody">
						<?= $complaint['text'];?>
							<?php
							$count = Complaint::getCountOfAnswersMy($complaint['id'], $user_id);
							$countStr = $count >= 1 ? '<b>есть ответы</b>' : 'нет ответа';
							echo $complaint['status'] == 0 ? '<span><a href="'.Yii::app()->createUrl('user/answer', array('complaint'=>$complaint['id'])).'"> Просмотреть ('.$countStr.')</a></span>' : '<span><a href="'.Yii::app()->createUrl('user/answer', array('complaint'=>$complaint['id'])).'"> Просмотреть</a></span>';
						?>	
						</div>
					</div>
						
						
					
				<?php endforeach;
				else:
					echo 'Нет жалоб';
				endif;
			
			?>
		</div>
	</div>
</section>